name: Variables Scope Demo
env:
  MY_WORKFLOW_VARIABLE: "This is my new workflow-level variable"

on:
  push:
    branches: [ main ] 

jobs:
  example-job:
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Workflow and Job Variables
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"

      - name: Display Step Variable
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
          echo "Job Variable: $MY_JOB_VARIABLE"
          echo "Step Variable: $MY_STEP_VARIABLE"
